services:
  database:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./db-data/:/var/lib/postgresql/data/"

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
